name: "release"
on: # rebuild any PRs and main branch changes
  release:
    types: [created]
jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: read
    steps:
      - name: Checking out!
        uses: actions/checkout@v3

      - name: Publish action package
        uses: actions-on-packages/package-action@0.4.2